# Generated by Django 4.2.7 on 2024-01-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("Username", models.CharField(max_length=50)),
                ("PASSWORD", models.CharField(max_length=50)),
                ("Confirm_Password", models.CharField(max_length=50)),
                ("EMAIL", models.EmailField(max_length=50)),
            ],
        ),
    ]
