# Generated by Django 4.2.7 on 2024-01-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Item", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Ord_ADD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Area", models.CharField(max_length=500)),
                ("City", models.CharField(max_length=100)),
                ("Pincode", models.CharField(max_length=6)),
                ("Mnumber", models.IntegerField()),
            ],
        ),
    ]
